spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rs_system?serverTimezone=Asia/Shanghai&useunicode=true&characterEncoding=utf8
    username: root
    password: 9161065501
  jpa:
    hibernate:
      ddl-auto: update
